"""Embed the checker so an installed blueprint needs no source checkout."""
import base64
import json
from pathlib import Path
import zlib


def render(source):
    encoded = base64.b64encode(zlib.compress(source, 9)).decode()
    loader = ('import base64,sys,zlib;sys.argv[1]=base64.b64decode(sys.argv[1]).decode();'
              f'exec(compile(zlib.decompress(base64.b64decode("{encoded}")),"<graphql-gate>","exec"))')
    return '''// Generated by scripts/generate_tool.py; edit scripts/gate.py.
// @tool graphql_contract_gate
// @description Validate or accept the GraphQL contract. Pass request={}; the stage hook supplies operation and review. Requires Python 3 with graphql-core 3.2.6.
// @param request object required "Empty object; authoritative arguments come from the hook"
// @requires shell filesystem

let encoded_request = encode_base64(to_json(params.request));
let loader = LOADER;
let command = "python3 -c '" + loader + "' " + encoded_request;
if command.len() > 120000 { throw "Contract gate request too large"; }
shell(command)
'''.replace("LOADER", json.dumps(loader))


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    (here.parent / "tools/graphql_contract_gate.rhai").write_text(render((here / "gate.py").read_bytes()))

    guide = (here.parent / "README.md").read_text()
    (here.parent / "tools/graphql_contract_guide.rhai").write_text(
        "// Generated by scripts/generate_tool.py; edit README.md.\n"
        "// @tool graphql_contract_guide\n"
        "// @description Read the exact GraphQL contract artifact format, acceptance criteria and pipeline integration instructions.\n\n"
        + json.dumps(guide) + "\n")
