"""Embed the stdlib kernel in a portable installed Rhai tool (no source checkout).

Run this after changing workspace.py. The generated tool is committed so the
CLI's existing bundled-agent installer needs no Python build dependency.
"""

import base64
import zlib
from pathlib import Path


def render(source: bytes) -> str:
    encoded = base64.b64encode(zlib.compress(source, level=9)).decode("ascii")
    # The source and request are base64, so neither can become shell syntax.
    return '''// Generated by scripts/generate_tool.py; edit scripts/workspace.py.
// @tool oracle_workspace
// @description Execute one bounded action under the canonical Oracle work order. Controllers pass an empty request. Workers pass action inspect/read/check/patch/seal and its fields; run/order authority is supplied by the runtime hook.
// @param request object required "Worker action and fields, or an empty object for a controller"
// @requires shell filesystem

let encoded_request = encode_base64(to_json(params.request));
let loader = "import base64,sys,zlib;sys.argv[1]=base64.b64decode(sys.argv[1]).decode('utf-8');exec(compile(zlib.decompress(base64.b64decode('SOURCE')),'<leviath-oracle>','exec'))";
// POSIX shell quoting is fixed; all variable shell arguments use base64.
let command = "python3 -c \\\"" + loader + "\\\" " + encoded_request;
if command.len() > 120000 { throw "Workspace request exceeds the shell argument budget; use a smaller patch"; }
shell(command)
'''.replace("SOURCE", encoded)


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    target = here.parent / "tools" / "oracle_workspace.rhai"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render((here / "workspace.py").read_bytes()), encoding="utf-8")
